name: E2E Workflow
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'pkg/**'
      - 'e2e/**'
      - 'cmd/**'
      - 'Dockerfile*'
      - 'go.mod'
      - 'go.sum'

jobs:

  init:
    outputs:
      tests: ${{ steps.e2es.outputs.result }}
    runs-on: [ default ]
    name: "Prepare E2E Scenarios"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      # find all e2e scenarios in the e2e directory and generate an array of scenario names
      - name: "E2E Detection"
        id: e2es
        run: |
          scenarios=$(find ${GITHUB_WORKSPACE}/e2e -type f -name 'e2e_test.go' -exec dirname {} \; | xargs -n 1 basename | jq -R -s -c 'split("\n")[:-1]')
          echo $scenarios
          echo "result=$scenarios" >> $GITHUB_OUTPUT

  e2e:
    name: "Run ${{ matrix.e2es }}(${{ matrix.k8s-version}}) E2E"
    if: needs.init.outputs.tests != '[]'
    needs: [ init ]
    runs-on: [ default ]
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [ "v1.30.10", "v1.31.6", "v1.32.2" ]
        e2es: ${{fromJson(needs.init.outputs.tests)}}
    steps:
      # run the e2e tests using composite common/workflows/e2e action
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: "E2E"
        id: e2e
        uses: cloudoperators/common/workflows/e2e@613b4beaa5b3a3e5bd31777778323431c92e77c4 # main
        with:
          k8s-version: ${{ matrix.k8s-version }}
          scenario: ${{ matrix.e2es }}
          admin-config: ${{ github.workspace }}/dev-env/greenhouse-admin-cluster.yaml
          remote-config: ${{ github.workspace }}/dev-env/greenhouse-remote-cluster.yaml

      # v4 upload-artifact needs unique names for each artifact (see https://github.com/actions/upload-artifact/tree/main?tab=readme-ov-file#not-uploading-to-the-same-artifact)
      - name: "Upload E2E Logs"
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        if: ${{ steps.e2e.outputs.result != '' }} # skip if nothing needs to be uploaded
        with:
          name: e2e-logs-${{ matrix.e2es }}-${{ matrix.k8s-version }}
          path: ${{steps.e2e.outputs.result}}
          retention-days: 7
          if-no-files-found: ignore

  artifacts:
    name: "Merge Artifacts"
    runs-on: [ default ]
    needs: [ e2e ]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: "Merge Uploads"
        continue-on-error: true # If there are no artifacts available, the merge step will fail so we need to continue on error
        uses: actions/upload-artifact/merge@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        with:
          name: e2e-logs
          pattern: e2e-logs-*
          retention-days: 7
          delete-merged: true

  # check if the e2e tests passed for all scenarios
  checksOK:
    name: "E2E Check"
    needs: [ artifacts, e2e ]
    runs-on: [ default ]
    if: always()
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: "Check if e2e passed"
        run: |
          if [ "${{ needs.e2e.result }}" == "success" ]; then
            echo "✅ E2E passed 🎉"
          else
            echo "❌ E2E failed 😭"
            exit 1
          fi
