name: Close inactive issues
on:
  schedule:
    - cron: "35 1 * * *"

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    uses: cloudoperators/common/.github/workflows/shared-stale.yaml@main
